# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/d2lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/d2kdi/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/samsung/d2kdi/proprietary/bin/thermald:system/bin/thermald \
    vendor/samsung/d2kdi/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/d2kdi/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/samsung/d2kdi/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/samsung/d2kdi/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/samsung/d2kdi/proprietary/vendor/firmware/bcm4334.hcd:system/vendor/firmware/bcm4334.hcd \
    vendor/samsung/d2kdi/proprietary/vendor/firmware/bcm4334_murata.hcd:system/vendor/firmware/bcm4334_murata.hcd \
    vendor/samsung/d2kdi/proprietary/vendor/firmware/bcm4334_semco.hcd:system/vendor/firmware/bcm4334_semco.hcd \
    vendor/samsung/d2kdi/proprietary/lib/hw/camera.vendor.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
    vendor/samsung/d2kdi/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/d2kdi/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
    vendor/samsung/d2kdi/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/d2kdi/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/d2kdi/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/d2kdi/proprietary/lib/libvdis.so:system/lib/libvdis.so \
    vendor/samsung/d2kdi/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/d2kdi/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_s5k6a3yx_default_video.so:system/lib/libchromatix_s5k6a3yx_default_video.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_s5k6a3yx_preview.so:system/lib/libchromatix_s5k6a3yx_preview.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_s5k6a3yx_smart_stay.so:system/lib/libchromatix_s5k6a3yx_smart_stay.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_s5k6a3yx_vt_hd.so:system/lib/libchromatix_s5k6a3yx_vt_hd.so \
    vendor/samsung/d2kdi/proprietary/lib/libchromatix_s5k6a3yx_vt.so:system/lib/libchromatix_s5k6a3yx_vt.so \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_GC.bin:system/cameradata/SlimISP_GC.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_GD.bin:system/cameradata/SlimISP_GD.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_GE.bin:system/cameradata/SlimISP_GE.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_GH.bin:system/cameradata/SlimISP_GH.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_JH.bin:system/cameradata/SlimISP_JH.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_PH.bin:system/cameradata/SlimISP_PH.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_WH.bin:system/cameradata/SlimISP_WH.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_ZC.bin:system/cameradata/SlimISP_ZC.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_ZD.bin:system/cameradata/SlimISP_ZD.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_ZE.bin:system/cameradata/SlimISP_ZE.bin \
    vendor/samsung/d2kdi/proprietary/cameradata/SlimISP_ZH.bin:system/cameradata/SlimISP_ZH.bin \
    vendor/samsung/d2kdi/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/samsung/d2kdi/proprietary/lib/hw/nfc.msm8960.so:system/lib/hw/nfc.msm8960.so \
    vendor/samsung/d2kdi/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/samsung/d2kdi/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/samsung/d2kdi/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/samsung/d2kdi/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/d2kdi/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/samsung/d2kdi/proprietary/etc/sec_config:system/etc/sec_config \
    vendor/samsung/d2kdi/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/d2kdi/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/d2kdi/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/d2kdi/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/d2kdi/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/samsung/d2kdi/proprietary/bin/sec-ril:system/bin/sec-ril \
    vendor/samsung/d2kdi/proprietary/blobs/gsm/lib/libril.so:system/blobs/gsm/lib/libril.so \
    vendor/samsung/d2kdi/proprietary/blobs/gsm/lib/libsec-ril.so:system/blobs/gsm/lib/libsec-ril.so \
    vendor/samsung/d2kdi/proprietary/blobs/r530/lib/libril.so:system/blobs/r530/lib/libril.so \
    vendor/samsung/d2kdi/proprietary/blobs/r530/lib/libsec-ril.so:system/blobs/r530/lib/libsec-ril.so \
    vendor/samsung/d2kdi/proprietary/blobs/spr/lib/libril.so:system/blobs/spr/lib/libril.so \
    vendor/samsung/d2kdi/proprietary/blobs/spr/lib/libsec-ril.so:system/blobs/spr/lib/libsec-ril.so \
    vendor/samsung/d2kdi/proprietary/blobs/vzw/lib/libril.so:system/blobs/vzw/lib/libril.so \
    vendor/samsung/d2kdi/proprietary/blobs/vzw/lib/libsec-ril.so:system/blobs/vzw/lib/libsec-ril.so \
    vendor/samsung/d2kdi/proprietary/blobs/kdi/lib/libril.so:system/blobs/kdi/lib/libril.so \
    vendor/samsung/d2kdi/proprietary/blobs/kdi/lib/libril-qc-qmi-1.so:system/blobs/kdi/lib/libril-qc-qmi-1.so \
    vendor/samsung/d2kdi/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/samsung/d2kdi/proprietary/lib/libakmd.so:system/lib/libakmd.so \
    vendor/samsung/d2kdi/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/samsung/d2kdi/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/samsung/d2kdi/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/samsung/d2kdi/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/d2kdi/proprietary/etc/wifi/bcmdhd_p2p.bin_b2:system/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/d2kdi/proprietary/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/d2kdi/proprietary/etc/wifi/bcmdhd_mfg.bin_b2:system/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/d2kdi/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/d2kdi/proprietary/etc/wifi/nvram_mfg.txt_murata:system/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/d2kdi/proprietary/etc/wifi/nvram_mfg.txt_murata_b2:system/etc/wifi/nvram_mfg.txt_murata_b2 \
    vendor/samsung/d2kdi/proprietary/etc/wifi/nvram_mfg.txt_semcosh:system/etc/wifi/nvram_mfg.txt_semcosh \
    vendor/samsung/d2kdi/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/d2kdi/proprietary/etc/wifi/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/d2kdi/proprietary/etc/wifi/nvram_net.txt_murata_b2:system/etc/wifi/nvram_net.txt_murata_b2 \
    vendor/samsung/d2kdi/proprietary/etc/wifi/nvram_net.txt_semcosh:system/etc/wifi/nvram_net.txt_semcosh
